///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String iconsAdd = 'assets/icons/add.svg';
  static const String iconsArrowDown = 'assets/icons/arrow-down.svg';
  static const String iconsArrowRight = 'assets/icons/arrow-right.svg';
  static const String iconsCardReceive = 'assets/icons/card-receive.svg';
  static const String iconsCardSend = 'assets/icons/card-send.svg';
  static const String iconsChart = 'assets/icons/chart.svg';
  static const String iconsDashboard = 'assets/icons/dashboard.svg';
  static const String iconsLogout = 'assets/icons/logout.svg';
  static const String iconsMoneys = 'assets/icons/moneys.svg';
  static const String iconsSetting = 'assets/icons/setting.svg';
  static const String iconsStatistics = 'assets/icons/statistics.svg';
  static const String iconsTransaction = 'assets/icons/transaction.svg';
  static const String iconsWallet = 'assets/icons/wallet.svg';
  static const String imagesBall1 = 'assets/images/ball1.png';
  static const String imagesBall2 = 'assets/images/ball2.png';
  static const String imagesBall3 = 'assets/images/ball3.png';

}
